#!/bin/bash
dir=`dirname $0`
dirIgor=$dir/../../../../igor
dirNetAtmo=$dirIgor/../../jack/netAtmo
python $dirNetAtmo/getCurrentWeather.py --json | python $dirIgor/igorVar.py --put application/json sensors/netAtmo
