#!/bin/bash
dir=`dirname $0`
dirIgor=$dir/../../../../igor
dirSmartMeter=$dirIgor/../../jack/smartMeter

curl http://$igor_host/p1?format=xml | python $dirIgor/igorVar.py --put application/xml sensors/smartMeter
