#!/bin/sh
echo "Content-Type: text/plain"
echo
echo ---------------- echoscript --------------------
echo user is "$user"
echo ------------------------------------------------
echo userData is "$userData"
echo ------------------------------------------------
