#!/bin/bash
dir=`dirname $0`
dirHomeServer=$dir/..
dirNetAtmo=$dir/../../../netAtmo
python $dirNetAtmo/getCurrentWeather.py --json | python $dirHomeServer/homeVar.py --put application/json sensors/netAtmo
