#!/bin/bash
dir=`dirname $0`
dirIgor=$dir/../../..
dirDHCP=$dirIgor/../

python $dirDHCP/dhcpleases.py --json --wrap --ping --arp -i client-hostname -i hardware -i ip-address -i alive -i arp -i ping | python $dirIgor/igorVar.py --put application/json sensors/dhcp
