#!/bin/bash
dir=`dirname $0`
dirHomeServer=$dir/../../..
dirDHCP=$dirHomeServer/../

python $dirDHCP/dhcpleases.py --json --wrap --ping --arp -i client-hostname -i hardware -i ip-address -i alive -i arp -i ping | python $dirHomeServer/homeVar.py --put application/json sensors/dhcp
