#!/bin/bash
dir=`dirname $0`
dirHomeServer=$dir/../../..
dirFitbit=$dirHomeServer/../../fitbit
case "x$user" in
x)
	echo $0: need user= argument
	exit 1
	;;
esac
case "x$pluginData" in
x)
	echo $0: no pluginData for user=$user
	exit 1
	;;
esac
echo $pluginData | python $dirFitbit/getFitbit.py --stdin | python $dirHomeServer/homeVar.py --put application/json sensors/fitbit/$user
