#!/bin/sh
### BEGIN INIT INFO
# Provides:          bleServer
# Required-Start:    bluetooth networking
# Required-Stop:     bluetooth networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Bluetooth availability monitoring daemon
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions
# Process name ( For display )
NAME=bleServer
# Daemon name, where is the actual executable
DAEMON=bleServer
DAEMON_ARGS="--port 9334 --nolog"

SCRIPT="$DAEMON $DAEMON_ARGS"
PIDFILE=/var/run/bleServer.pid

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="PATH=$PATH $SCRIPT & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
